[project]
name = 'Intellectual-Property-Licensing-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.ip-asset-management]
path = 'contracts/ip-asset-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.license-agreement]
path = 'contracts/license-agreement.clar'
clarity_version = 2
epoch = 2.5

[contracts.usage-tracking]
path = 'contracts/usage-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
